# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7b8cb6a157461156221413e3fa9eef3c7b50979bfc509a67d9fb9e4a855f818c98c9f517b134b2f60a69128ad1a2544f2c54a4f1c6626c45a80f1c482379fa

test:
  secret_key_base: 024edba26e12ce9a32be20570b9f8eb1c0da8c7f17727a0489f40a64fbba7f33e9e4f97e983f8d57260d3bd8be296692d0e26bcaaec3cb2df99fb9928faaf438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
